channels:
  - conda-forge
  - bioconda
dependencies:
  - c-blosc2
  - libsodium
  - openjpeg
  - libgfortran
  - zstd
  - brotli-python
  - stack_data
  - dcor
  - jupyter_core
  - tornado
  - joblib
  - libopenblas
  - libhwloc
  - libiconv
  - py-xgboost
  - yaml
  - bzip2
  - freetype
  - zeromq
  - libbrotlidec
  - libffi
  - libxgboost
  - array-api-compat
  - hdf5
  - legendkit
  - py-cpuinfo
  - readline
  - six
  - colorcet
  - docrep
  - libexpat
  - libcblas
  - jupyterlab_widgets
  - libxml2-devel
  - numcodecs
  - numpy
  - xarray
  - c-ares
  - libtiff
  - pthread-stubs
  - krb5
  - matplotlib-base
  - igraph
  - h5py
  - legacy-api-wrap
  - kiwisolver
  - libxml2-16
  - pexpect
  - libnghttp2
  - libedit
  - backports.zstd
  - certifi
  - numexpr
  - libfreetype
  - libxcb
  - debugpy
  - brotli-bin
  - sqlite
  - numba
  - xorg-libxdmcp
  - libgcc
  - liblapack
  - pandas
  - parso
  - python-dateutil
  - donfig
  - appnope
  - icu
  - leidenalg
  - libleidenalg
  - comm
  - widgetsnbextension
  - tk
  - brotli
  - libxml2
  - scipy
  - ncurses
  - cached-property
  - libdeflate
  - libbrotlienc
  - libaec
  - session-info2
  - glpk
  - python_abi
  - pillow
  - libcxx
  - lcms2
  - deprecated
  - statsmodels
  - patsy
  - lz4-c
  - python-igraph
  - llvmlite
  - zarr
  - wcwidth
  - typing-extensions
  - pyzmq
  - zlib
  - param
  - arpack
  - ipython
  - asttokens
  - texttable
  - pyyaml
  - pygments
  - h2
  - requests
  - threadpoolctl
  - libev
  - libcrc32c
  - llvm-openmp
  - natsort
  - fonttools
  - xorg-libxau
  - pyct
  - seaborn
  - libgfortran5
  - wheel
  - datashader
  - pynndescent
  - jedi
  - libblas
  - tqdm
  - typing_extensions
  - pure_eval
  - decorator
  - networkx
  - gseapy
  - snappy
  - pytables
  - decoupler-py
  - wrapt
  - blosc
  - scikit-learn
  - pyparsing
  - pyopengl
  - pip
  - cached_property
  - prompt-toolkit
  - setuptools
  - packaging
  - zlib-ng
  - libfreetype6
  - ipywidgets
  - hpack
  - ipython_pygments_lexers
  - matplotlib-inline
  - jupyter_client
  - libjpeg-turbo
  - nest-asyncio
  - cycler
  - libcurl
  - urllib3
  - expat
  - munkres
  - multipledispatch
  - google-crc32c
  - liblzma
  - lerc
  - gmp
  - libzlib
  - toolz
  - anndata
  - platformdirs
  - psutil
  - libwebp-base
  - _openmp_mutex
  - msgpack-python
  - pysocks
  - hyperframe
  - contourpy
  - umap-learn
  - libsqlite
  - ca-certificates
  - xgboost
  - adjusttext
  - openssl
  - scanpy
  - python
  - traitlets
  - tzdata
  - charset-normalizer
  - idna
  - libbrotlicommon
  - libpng
  - ptyprocess
  - tbb
  - unicodedata2
  - ipykernel
  - executing
  - libssh2
  - marsilea
  - seaborn-base
  - _python_abi3_support
  - appdirs
  - bioservices
  - cpython
  - libuv
  - lxml
  - suds-community
  - beautifulsoup4
  - zope.event
  - colorlog
  - colorama
  - easydev
  - grequests
  - greenlet
  - pycparser
  - xmltodict
  - requests_cache
  - cffi
  - click
  - html5lib
  - gevent
  - python-gil
  - webencodings
  - libxslt
  - qhull
  - zope.interface
  - soupsieve
  - libmpdec
  - celltypist
  

